version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "autopep8"